#docker-compose up -d câu lệnh chạy docker trên cmd
services: #định nghĩa danh sách các dịch vụ(container) chạy cùng nhau
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/tmp/kraft-combined-logs
  redis:
    image: redis:8.0-M03-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  elastic-search:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - default
volumes:
  kafka-data:
    driver: local #dòng này để kể cả khi tắt container dữ liệu cũng không bị mất
  cache: #phải có dòng anyf thì phần volumes của redis mưới tham chiếu ến mà tạo file /data được
    driver: local
  es-data:
    driver: local